services:
  php:
    build: .
    container_name: php-krs-container
    image: php-krs-container:1.0.0
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
